### ISSUE TITLE
if I set the ctx.request.headers['content-encoding'] = 'utf-8'，there will be an error。

### ISSUE THREAD

**Issue by lizuncong** [stream-utils/inflation#16]
Error: Unsupported Content-Encoding: utf-8
      at inflate (/Users/lizuncong/Documents/SheInProjects/mes_wechat/node_modules/inflation/index.js:23:15)
      at /Users/lizuncong/Documents/SheInProjects/mes_wechat/node_modules/co-body/lib/json.js:41:18

**Comment by jingxinxin** [comment]
@lizuncong I have encountered the same problem and have submitted pullrequests to be fixed. You can have a look https://github.com/stream-utils/inflation/pull/17#issue-503219025
